import Head from "next/head";
import { Inter } from "next/font/google";
import { useEffect, useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [loadDate, setLoadDate] = useState("");
  useEffect(() => {
    localStorage.setItem("loadDate", String(new Date()));
    setLoadDate(String(localStorage.getItem("loadDate")));
  }, []);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Loaded at {loadDate}</h1>
      </main>
    </>
  );
}
